<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["id" => "1", "name" => "Afghanistan", "short_name" => "AF"],
            ["id" => "2", "name" => "Albania", "short_name" => "AL"],
            ["id" => "3", "name" => "Algeria", "short_name" => "DZ"],
            ["id" => "4", "name" => "American Samoa", "short_name" => "AS"],
            ["id" => "5", "name" => "Andorra", "short_name" => "AD"],
            ["id" => "6", "name" => "Angola", "short_name" => "AO"],
            ["id" => "7", "name" => "Anguilla", "short_name" => "AI"],
            ["id" => "8", "name" => "Antarctica", "short_name" => "AQ"],
            ["id" => "9", "name" => "Antigua and Barbuda", "short_name" => "AG"],
            ["id" => "10", "name" => "Argentina", "short_name" => "AR"],
            ["id" => "11", "name" => "Armenia", "short_name" => "AM"],
            ["id" => "12", "name" => "Aruba", "short_name" => "AW"],
            ["id" => "13", "name" => "Australia", "short_name" => "AU"],
            ["id" => "14", "name" => "Austria", "short_name" => "AT"],
            ["id" => "15", "name" => "Azerbaijan", "short_name" => "AZ"],
            ["id" => "16", "name" => "Bahamas", "short_name" => "BS"],
            ["id" => "17", "name" => "Bahrain", "short_name" => "BH"],
            ["id" => "18", "name" => "Bangladesh", "short_name" => "BD"],
            ["id" => "19", "name" => "Barbados", "short_name" => "BB"],
            ["id" => "20", "name" => "Belarus", "short_name" => "BY"],
            ["id" => "21", "name" => "Belgium", "short_name" => "BE"],
            ["id" => "22", "name" => "Belize", "short_name" => "BZ"],
            ["id" => "23", "name" => "Benin", "short_name" => "BJ"],
            ["id" => "24", "name" => "Bermuda", "short_name" => "BM"],
            ["id" => "25", "name" => "Bhutan", "short_name" => "BT"],
            ["id" => "26", "name" => "Bolivia", "short_name" => "BO"],
            ["id" => "27", "name" => "Bosnia and Herzegovina", "short_name" => "BA"],
            ["id" => "28", "name" => "Botswana", "short_name" => "BW"],
            ["id" => "29", "name" => "Bouvet Island", "short_name" => "BV"],
            ["id" => "30", "name" => "Brazil", "short_name" => "BR"],
            ["id" => "31", "name" => "British Indian Ocean Territory", "short_name" => "IO"],
            ["id" => "32", "name" => "Brunei Darussalam", "short_name" => "BN"],
            ["id" => "33", "name" => "Bulgaria", "short_name" => "BG"],
            ["id" => "34", "name" => "Burkina Faso", "short_name" => "BF"],
            ["id" => "35", "name" => "Burundi", "short_name" => "BI"],
            ["id" => "36", "name" => "Cambodia", "short_name" => "KH"],
            ["id" => "37", "name" => "Cameroon", "short_name" => "CM"],
            ["id" => "38", "name" => "Canada", "short_name" => "CA"],
            ["id" => "39", "name" => "Cabo Verde", "short_name" => "CV"],
            ["id" => "40", "name" => "Cayman Islands", "short_name" => "KY"],
            ["id" => "41", "name" => "Central African Republic", "short_name" => "CF"],
            ["id" => "42", "name" => "Chad", "short_name" => "TD"],
            ["id" => "43", "name" => "Chile", "short_name" => "CL"],
            ["id" => "44", "name" => "China", "short_name" => "CN"],
            ["id" => "45", "name" => "Christmas Island", "short_name" => "CX"],
            ["id" => "46", "name" => "Cocos (Keeling) Islands", "short_name" => "CC"],
            ["id" => "47", "name" => "Colombia", "short_name" => "CO"],
            ["id" => "48", "name" => "Comoros", "short_name" => "KM"],
            ["id" => "49", "name" => "Congo", "short_name" => "CG"],
            ["id" => "50", "name" => "Cook Islands", "short_name" => "CK"],
            ["id" => "51", "name" => "Costa Rica", "short_name" => "CR"],
            ["id" => "52", "name" => "Cote d'Ivoire", "short_name" => "CI"],
            ["id" => "53", "name" => "Croatia", "short_name" => "HR"],
            ["id" => "54", "name" => "Cuba", "short_name" => "CU"],
            ["id" => "55", "name" => "Cyprus", "short_name" => "CY"],
            ["id" => "56", "name" => "Czech Republic", "short_name" => "CZ"],
            ["id" => "57", "name" => "Denmark", "short_name" => "DK"],
            ["id" => "58", "name" => "Djibouti", "short_name" => "DJ"],
            ["id" => "59", "name" => "Dominica", "short_name" => "DM"],
            ["id" => "60", "name" => "Dominican Republic", "short_name" => "DO"],
            ["id" => "61", "name" => "East Timor", "short_name" => "TL"],
            ["id" => "62", "name" => "Ecuador", "short_name" => "EC"],
            ["id" => "63", "name" => "Egypt", "short_name" => "EG"],
            ["id" => "64", "name" => "El Salvador", "short_name" => "SV"],
            ["id" => "65", "name" => "Equatorial Guinea", "short_name" => "GQ"],
            ["id" => "66", "name" => "Eritrea", "short_name" => "ER"],
            ["id" => "67", "name" => "Estonia", "short_name" => "EE"],
            ["id" => "68", "name" => "Ethiopia", "short_name" => "ET"],
            ["id" => "69", "name" => "Falkland Islands (Malvinas)", "short_name" => "FK"],
            ["id" => "70", "name" => "Faroe Islands", "short_name" => "FO"],
            ["id" => "71", "name" => "Fiji", "short_name" => "FJ"],
            ["id" => "72", "name" => "Finland", "short_name" => "FI"],
            ["id" => "73", "name" => "France", "short_name" => "FR"],
            ["id" => "74", "name" => "French Guiana", "short_name" => "GF"],
            ["id" => "75", "name" => "French Polynesia", "short_name" => "PF"],
            ["id" => "76", "name" => "French Southern Territories", "short_name" => "TF"],
            ["id" => "77", "name" => "Gabon", "short_name" => "GA"],
            ["id" => "78", "name" => "Gambia", "short_name" => "GM"],
            ["id" => "79", "name" => "Georgia", "short_name" => "GE"],
            ["id" => "80", "name" => "Germany", "short_name" => "DE"],
            ["id" => "81", "name" => "Ghana", "short_name" => "GH"],
            ["id" => "82", "name" => "Gibraltar", "short_name" => "GI"],
            ["id" => "83", "name" => "Greece", "short_name" => "GR"],
            ["id" => "84", "name" => "Greenland", "short_name" => "GL"],
            ["id" => "85", "name" => "Grenada", "short_name" => "GD"],
            ["id" => "86", "name" => "Guadeloupe", "short_name" => "GP"],
            ["id" => "87", "name" => "Guam", "short_name" => "GUAM"],
            ["id" => "88", "name" => "Guatemala", "short_name" => "GT"],
            ["id" => "89", "name" => "Guernsey", "short_name" => "GG"],
            ["id" => "90", "name" => "Guinea", "short_name" => "GN"],
            ["id" => "91", "name" => "Guinea-Bissau", "short_name" => "GW"],
            ["id" => "92", "name" => "Guyana", "short_name" => "GY"],
            ["id" => "93", "name" => "Haiti", "short_name" => "HT"],
            ["id" => "94", "name" => "Honduras", "short_name" => "HN"],
            ["id" => "95", "name" => "Hong Kong", "short_name" => "HK"],
            ["id" => "96", "name" => "Hungary", "short_name" => "HU"],
            ["id" => "97", "name" => "Iceland", "short_name" => "IS"],
            ["id" => "98", "name" => "India", "short_name" => "IN"],
            ["id" => "99", "name" => "Indonesia", "short_name" => "ID"],
            ["id" => "100", "name" => "Iran, Islamic Republic of", "short_name" => "IR"],
            ["id" => "101", "name" => "Iraq", "short_name" => "IQ"],
            ["id" => "102", "name" => "Ireland", "short_name" => "IE"],
            ["id" => "103", "name" => "Isle of Man", "short_name" => "IM"],
            ["id" => "104", "name" => "Israel", "short_name" => "IL"],
            ["id" => "105", "name" => "Italy", "short_name" => "IT"],
            ["id" => "106", "name" => "Jamaica", "short_name" => "JM"],
            ["id" => "107", "name" => "Japan", "short_name" => "JP"],
            ["id" => "108", "name" => "Jersey", "short_name" => "JE"],
            ["id" => "109", "name" => "Jordan", "short_name" => "JO"],
            ["id" => "110", "name" => "Kazakhstan", "short_name" => "KZ"],
            ["id" => "111", "name" => "Kenya", "short_name" => "KE"],
            ["id" => "112", "name" => "Kiribati", "short_name" => "KI"],
            ["id" => "113", "name" => "Korea, Democratic People's Republic of", "short_name" => "KP"],
            ["id" => "114", "name" => "Korea, Republic of", "short_name" => "KR"],
            ["id" => "115", "name" => "Kuwait", "short_name" => "KW"],
            ["id" => "116", "name" => "Kyrgyzstan", "short_name" => "KG"],
            ["id" => "117", "name" => "Lao People's Democratic Republic", "short_name" => "LA"],
            ["id" => "118", "name" => "Latvia", "short_name" => "LV"],
            ["id" => "119", "name" => "Lebanon", "short_name" => "LB"],
            ["id" => "120", "name" => "Lesotho", "short_name" => "LS"],
            ["id" => "121", "name" => "Liberia", "short_name" => "LR"],
            ["id" => "122", "name" => "Libyan Arab Jamahiriya", "short_name" => "LY"],
            ["id" => "123", "name" => "Liechtenstein", "short_name" => "LI"],
            ["id" => "124", "name" => "Lithuania", "short_name" => "LT"],
            ["id" => "125", "name" => "Luxembourg", "short_name" => "LU"],
            ["id" => "126", "name" => "Macau", "short_name" => "MO"],
            ["id" => "127", "name" => "Macedonia", "short_name" => "MK"],
            ["id" => "128", "name" => "Madagascar", "short_name" => "MG"],
            ["id" => "129", "name" => "Malawi", "short_name" => "MW"],
            ["id" => "130", "name" => "Malaysia", "short_name" => "MY"],
            ["id" => "131", "name" => "Maldives", "short_name" => "MV"],
            ["id" => "132", "name" => "Mali", "short_name" => "ML"],
            ["id" => "133", "name" => "Malta", "short_name" => "MT"],
            ["id" => "134", "name" => "Marshall Islands", "short_name" => "MI"],
            ["id" => "135", "name" => "Martinique", "short_name" => "MQ"],
            ["id" => "136", "name" => "Mauritania", "short_name" => "MR"],
            ["id" => "137", "name" => "Mauritius", "short_name" => "MU"],
            ["id" => "138", "name" => "Mexico", "short_name" => "MX"],
            ["id" => "139", "name" => "Moldova, Republic of", "short_name" => "MD"],
            ["id" => "140", "name" => "Monaco", "short_name" => "MC"],
            ["id" => "141", "name" => "Mongolia", "short_name" => "MN"],
            ["id" => "142", "name" => "Montserrat", "short_name" => "MS"],
            ["id" => "143", "name" => "Morocco", "short_name" => "MA"],
            ["id" => "144", "name" => "Mozambique", "short_name" => "MZ"],
            ["id" => "145", "name" => "Myanmar", "short_name" => "MM"],
            ["id" => "146", "name" => "Namibia", "short_name" => "NA"],
            ["id" => "147", "name" => "Nauru", "short_name" => "NR"],
            ["id" => "148", "name" => "Nepal", "short_name" => "NP"],
            ["id" => "149", "name" => "Netherlands", "short_name" => "NL"],
            ["id" => "150", "name" => "Netherlands Antilles", "short_name" => "ANT"],
            ["id" => "151", "name" => "Neutral Zone (Saudi/Iraq)", "short_name" => "NT"],
            ["id" => "152", "name" => "New Caledonia", "short_name" => "NC"],
            ["id" => "153", "name" => "New Zealand", "short_name" => "NZ"],
            ["id" => "154", "name" => "Nicaragua", "short_name" => "NI"],
            ["id" => "155", "name" => "Niger", "short_name" => "NE"],
            ["id" => "156", "name" => "Nigeria", "short_name" => "NG"],
            ["id" => "157", "name" => "Niue", "short_name" => "NU"],
            ["id" => "158", "name" => "Norfolk Island", "short_name" => "NF"],
            ["id" => "159", "name" => "Northern Ireland", "short_name" => "NIR"],
            ["id" => "160", "name" => "Northern Mariana Islands", "short_name" => "NMI"],
            ["id" => "161", "name" => "Norway", "short_name" => "NO"],
            ["id" => "162", "name" => "Oman", "short_name" => "OM"],
            ["id" => "163", "name" => "Pakistan", "short_name" => "PK"],
            ["id" => "164", "name" => "Palau", "short_name" => "PAL"],
            ["id" => "165", "name" => "Palestinian Territory", "short_name" => "PS"],
            ["id" => "166", "name" => "Panama", "short_name" => "PA"],
            ["id" => "167", "name" => "Panama Canal Zone", "short_name" => "PZ"],
            ["id" => "168", "name" => "Papua New Guinea", "short_name" => "PG"],
            ["id" => "169", "name" => "Paraguay", "short_name" => "PY"],
            ["id" => "170", "name" => "Peru", "short_name" => "PE"],
            ["id" => "171", "name" => "Philippines", "short_name" => "PH"],
            ["id" => "172", "name" => "Pitcairn Islands", "short_name" => "PN"],
            ["id" => "173", "name" => "Poland", "short_name" => "PL"],
            ["id" => "174", "name" => "Portugal", "short_name" => "PT"],
            ["id" => "175", "name" => "Puerto Rico", "short_name" => "PR"],
            ["id" => "176", "name" => "Qatar", "short_name" => "QA"],
            ["id" => "177", "name" => "Reunion", "short_name" => "RE"],
            ["id" => "178", "name" => "Romania", "short_name" => "RO"],
            ["id" => "179", "name" => "Russian Federation", "short_name" => "RU"],
            ["id" => "180", "name" => "Saint Kitts and Nevis", "short_name" => "KN"],
            ["id" => "181", "name" => "Saint Lucia", "short_name" => "LC"],
            ["id" => "182", "name" => "Samoa", "short_name" => "WS"],
            ["id" => "183", "name" => "San Marino", "short_name" => "SM"],
            ["id" => "184", "name" => "Sao Tome and Principe", "short_name" => "ST"],
            ["id" => "185", "name" => "Saudi Arabia", "short_name" => "SA"],
            ["id" => "186", "name" => "Scotland", "short_name" => "SCT"],
            ["id" => "187", "name" => "Senegal", "short_name" => "SN"],
            ["id" => "188", "name" => "Seychelles", "short_name" => "SC"],
            ["id" => "189", "name" => "Sierra Leone", "short_name" => "SL"],
            ["id" => "190", "name" => "Singapore", "short_name" => "SG"],
            ["id" => "191", "name" => "Slovakia", "short_name" => "SK"],
            ["id" => "192", "name" => "Slovenia", "short_name" => "SI"],
            ["id" => "193", "name" => "Solomon Islands", "short_name" => "SB"],
            ["id" => "194", "name" => "Somalia", "short_name" => "SO"],
            ["id" => "195", "name" => "South Africa", "short_name" => "ZA"],
            ["id" => "196", "name" => "Spain", "short_name" => "ES"],
            ["id" => "197", "name" => "Sri Lanka", "short_name" => "LK"],
            ["id" => "198", "name" => "Saint Helena", "short_name" => "SH"],
            ["id" => "199", "name" => "Saint Pierre and Miquelon", "short_name" => "PM"],
            ["id" => "200", "name" => "Saint Vincent and the Grenadines", "short_name" => "VC"],
            ["id" => "201", "name" => "Sudan", "short_name" => "SD"],
            ["id" => "202", "name" => "Suriname", "short_name" => "SR"],
            ["id" => "203", "name" => "Svalbard and Jan Mayen", "short_name" => "SJ"],
            ["id" => "204", "name" => "Swaziland", "short_name" => "SZ"],
            ["id" => "205", "name" => "Sweden", "short_name" => "SE"],
            ["id" => "206", "name" => "Switzerland", "short_name" => "CH"],
            ["id" => "207", "name" => "Syrian Arab Republic", "short_name" => "SY"],
            ["id" => "208", "name" => "Taiwan", "short_name" => "TW"],
            ["id" => "209", "name" => "Tajikistan", "short_name" => "TJ"],
            ["id" => "210", "name" => "Tanzania, United Republic of", "short_name" => "TZ"],
            ["id" => "211", "name" => "Thailand", "short_name" => "TH"],
            ["id" => "212", "name" => "Togo", "short_name" => "TG"],
            ["id" => "213", "name" => "Tokelau", "short_name" => "TK"],
            ["id" => "214", "name" => "Tonga", "short_name" => "TO"],
            ["id" => "215", "name" => "Trinidad and Tobago", "short_name" => "TT"],
            ["id" => "216", "name" => "Tunisia", "short_name" => "TN"],
            ["id" => "217", "name" => "Turkey", "short_name" => "TR"],
            ["id" => "218", "name" => "Turkmenistan", "short_name" => "TM"],
            ["id" => "219", "name" => "Turks and Caicos Islands", "short_name" => "TC"],
            ["id" => "220", "name" => "Tuvalu", "short_name" => "TV"],
            ["id" => "221", "name" => "United States Minor Outlying Islands", "short_name" => "UMI"],
            ["id" => "222", "name" => "Uganda", "short_name" => "UG"],
            ["id" => "223", "name" => "Ukraine", "short_name" => "UA"],
            ["id" => "224", "name" => "United Arab Emirates", "short_name" => "AE"],
            ["id" => "225", "name" => "United Kingdom", "short_name" => "GB"],
            ["id" => "226", "name" => "United States", "short_name" => "US"],
            ["id" => "227", "name" => "Uruguay", "short_name" => "UY"],
            ["id" => "228", "name" => "Uzbekistan", "short_name" => "UZ"],
            ["id" => "229", "name" => "Vanuatu", "short_name" => "VU"],
            ["id" => "230", "name" => "Holy See (Vatican City State)", "short_name" => "VA"],
            ["id" => "231", "name" => "Venezuela", "short_name" => "VE"],
            ["id" => "232", "name" => "Vietnam", "short_name" => "VN"],
            ["id" => "233", "name" => "Virgin Islands, British", "short_name" => "VG"],
            ["id" => "234", "name" => "Virgin Islands, U.S.", "short_name" => "VUUSA"],
            ["id" => "235", "name" => "Wales", "short_name" => "WLS"],
            ["id" => "236", "name" => "Wallis and Futuna", "short_name" => "WF"],
            ["id" => "237", "name" => "Western Sahara", "short_name" => "EH"],
            ["id" => "238", "name" => "Yemen", "short_name" => "YE"],
            ["id" => "240", "name" => "Congo, Democratic Republic of the", "short_name" => "CD"],
            ["id" => "241", "name" => "Zambia", "short_name" => "ZM"],
            ["id" => "242", "name" => "Zimbabwe", "short_name" => "ZW"],
            ["id" => "244", "name" => "Serbia", "short_name" => "RS"],
            ["id" => "245", "name" => "Montenegro", "short_name" => "ME"],
            ["id" => "246", "name" => "Kosovo", "short_name" => "KSV"],
            ["id" => "243", "name" => "Worldwide", "short_name" => "WW"],
        ];

        foreach ($data as $country) {
            Country::create($country);
        }
    }
}
