<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["id" => "1", "title" => "Afghanistan", "iso_code" => "AF"],
            ["id" => "2", "title" => "Albania", "iso_code" => "AL"],
            ["id" => "3", "title" => "Algeria", "iso_code" => "DZ"],
            ["id" => "4", "title" => "American Samoa", "iso_code" => "AS"],
            ["id" => "5", "title" => "Andorra", "iso_code" => "AD"],
            ["id" => "6", "title" => "Angola", "iso_code" => "AO"],
            ["id" => "7", "title" => "Anguilla", "iso_code" => "AI"],
            ["id" => "8", "title" => "Antarctica", "iso_code" => "AQ"],
            ["id" => "9", "title" => "Antigua and Barbuda", "iso_code" => "AG"],
            ["id" => "10", "title" => "Argentina", "iso_code" => "AR"],
            ["id" => "11", "title" => "Armenia", "iso_code" => "AM"],
            ["id" => "12", "title" => "Aruba", "iso_code" => "AW"],
            ["id" => "13", "title" => "Australia", "iso_code" => "AU"],
            ["id" => "14", "title" => "Austria", "iso_code" => "AT"],
            ["id" => "15", "title" => "Azerbaijan", "iso_code" => "AZ"],
            ["id" => "16", "title" => "Bahamas", "iso_code" => "BS"],
            ["id" => "17", "title" => "Bahrain", "iso_code" => "BH"],
            ["id" => "18", "title" => "Bangladesh", "iso_code" => "BD"],
            ["id" => "19", "title" => "Barbados", "iso_code" => "BB"],
            ["id" => "20", "title" => "Belarus", "iso_code" => "BY"],
            ["id" => "21", "title" => "Belgium", "iso_code" => "BE"],
            ["id" => "22", "title" => "Belize", "iso_code" => "BZ"],
            ["id" => "23", "title" => "Benin", "iso_code" => "BJ"],
            ["id" => "24", "title" => "Bermuda", "iso_code" => "BM"],
            ["id" => "25", "title" => "Bhutan", "iso_code" => "BT"],
            ["id" => "26", "title" => "Bolivia", "iso_code" => "BO"],
            ["id" => "27", "title" => "Bosnia and Herzegovina", "iso_code" => "BA"],
            ["id" => "28", "title" => "Botswana", "iso_code" => "BW"],
            ["id" => "29", "title" => "Bouvet Island", "iso_code" => "BV"],
            ["id" => "30", "title" => "Brazil", "iso_code" => "BR"],
            ["id" => "31", "title" => "British Indian Ocean Territory", "iso_code" => "IO"],
            ["id" => "32", "title" => "Brunei Darussalam", "iso_code" => "BN"],
            ["id" => "33", "title" => "Bulgaria", "iso_code" => "BG"],
            ["id" => "34", "title" => "Burkina Faso", "iso_code" => "BF"],
            ["id" => "35", "title" => "Burundi", "iso_code" => "BI"],
            ["id" => "36", "title" => "Cambodia", "iso_code" => "KH"],
            ["id" => "37", "title" => "Cameroon", "iso_code" => "CM"],
            ["id" => "38", "title" => "Canada", "iso_code" => "CA"],
            ["id" => "39", "title" => "Cabo Verde", "iso_code" => "CV"],
            ["id" => "40", "title" => "Cayman Islands", "iso_code" => "KY"],
            ["id" => "41", "title" => "Central African Republic", "iso_code" => "CF"],
            ["id" => "42", "title" => "Chad", "iso_code" => "TD"],
            ["id" => "43", "title" => "Chile", "iso_code" => "CL"],
            ["id" => "44", "title" => "China", "iso_code" => "CN"],
            ["id" => "45", "title" => "Christmas Island", "iso_code" => "CX"],
            ["id" => "46", "title" => "Cocos (Keeling) Islands", "iso_code" => "CC"],
            ["id" => "47", "title" => "Colombia", "iso_code" => "CO"],
            ["id" => "48", "title" => "Comoros", "iso_code" => "KM"],
            ["id" => "49", "title" => "Congo", "iso_code" => "CG"],
            ["id" => "50", "title" => "Cook Islands", "iso_code" => "CK"],
            ["id" => "51", "title" => "Costa Rica", "iso_code" => "CR"],
            ["id" => "52", "title" => "Cote d'Ivoire", "iso_code" => "CI"],
            ["id" => "53", "title" => "Croatia", "iso_code" => "HR"],
            ["id" => "54", "title" => "Cuba", "iso_code" => "CU"],
            ["id" => "55", "title" => "Cyprus", "iso_code" => "CY"],
            ["id" => "56", "title" => "Czech Republic", "iso_code" => "CZ"],
            ["id" => "57", "title" => "Denmark", "iso_code" => "DK"],
            ["id" => "58", "title" => "Djibouti", "iso_code" => "DJ"],
            ["id" => "59", "title" => "Dominica", "iso_code" => "DM"],
            ["id" => "60", "title" => "Dominican Republic", "iso_code" => "DO"],
            ["id" => "61", "title" => "East Timor", "iso_code" => "TL"],
            ["id" => "62", "title" => "Ecuador", "iso_code" => "EC"],
            ["id" => "63", "title" => "Egypt", "iso_code" => "EG"],
            ["id" => "64", "title" => "El Salvador", "iso_code" => "SV"],
            ["id" => "65", "title" => "Equatorial Guinea", "iso_code" => "GQ"],
            ["id" => "66", "title" => "Eritrea", "iso_code" => "ER"],
            ["id" => "67", "title" => "Estonia", "iso_code" => "EE"],
            ["id" => "68", "title" => "Ethiopia", "iso_code" => "ET"],
            ["id" => "69", "title" => "Falkland Islands (Malvinas)", "iso_code" => "FK"],
            ["id" => "70", "title" => "Faroe Islands", "iso_code" => "FO"],
            ["id" => "71", "title" => "Fiji", "iso_code" => "FJ"],
            ["id" => "72", "title" => "Finland", "iso_code" => "FI"],
            ["id" => "73", "title" => "France", "iso_code" => "FR"],
            ["id" => "74", "title" => "French Guiana", "iso_code" => "GF"],
            ["id" => "75", "title" => "French Polynesia", "iso_code" => "PF"],
            ["id" => "76", "title" => "French Southern Territories", "iso_code" => "TF"],
            ["id" => "77", "title" => "Gabon", "iso_code" => "GA"],
            ["id" => "78", "title" => "Gambia", "iso_code" => "GM"],
            ["id" => "79", "title" => "Georgia", "iso_code" => "GE"],
            ["id" => "80", "title" => "Germany", "iso_code" => "DE"],
            ["id" => "81", "title" => "Ghana", "iso_code" => "GH"],
            ["id" => "82", "title" => "Gibraltar", "iso_code" => "GI"],
            ["id" => "83", "title" => "Greece", "iso_code" => "GR"],
            ["id" => "84", "title" => "Greenland", "iso_code" => "GL"],
            ["id" => "85", "title" => "Grenada", "iso_code" => "GD"],
            ["id" => "86", "title" => "Guadeloupe", "iso_code" => "GP"],
            ["id" => "87", "title" => "Guam", "iso_code" => "GUAM"],
            ["id" => "88", "title" => "Guatemala", "iso_code" => "GT"],
            ["id" => "89", "title" => "Guernsey", "iso_code" => "GG"],
            ["id" => "90", "title" => "Guinea", "iso_code" => "GN"],
            ["id" => "91", "title" => "Guinea-Bissau", "iso_code" => "GW"],
            ["id" => "92", "title" => "Guyana", "iso_code" => "GY"],
            ["id" => "93", "title" => "Haiti", "iso_code" => "HT"],
            ["id" => "94", "title" => "Honduras", "iso_code" => "HN"],
            ["id" => "95", "title" => "Hong Kong", "iso_code" => "HK"],
            ["id" => "96", "title" => "Hungary", "iso_code" => "HU"],
            ["id" => "97", "title" => "Iceland", "iso_code" => "IS"],
            ["id" => "98", "title" => "India", "iso_code" => "IN"],
            ["id" => "99", "title" => "Indonesia", "iso_code" => "ID"],
            ["id" => "100", "title" => "Iran, Islamic Republic of", "iso_code" => "IR"],
            ["id" => "101", "title" => "Iraq", "iso_code" => "IQ"],
            ["id" => "102", "title" => "Ireland", "iso_code" => "IE"],
            ["id" => "103", "title" => "Isle of Man", "iso_code" => "IM"],
            ["id" => "104", "title" => "Israel", "iso_code" => "IL"],
            ["id" => "105", "title" => "Italy", "iso_code" => "IT"],
            ["id" => "106", "title" => "Jamaica", "iso_code" => "JM"],
            ["id" => "107", "title" => "Japan", "iso_code" => "JP"],
            ["id" => "108", "title" => "Jersey", "iso_code" => "JE"],
            ["id" => "109", "title" => "Jordan", "iso_code" => "JO"],
            ["id" => "110", "title" => "Kazakhstan", "iso_code" => "KZ"],
            ["id" => "111", "title" => "Kenya", "iso_code" => "KE"],
            ["id" => "112", "title" => "Kiribati", "iso_code" => "KI"],
            ["id" => "113", "title" => "Korea, Democratic People's Republic of", "iso_code" => "KP"],
            ["id" => "114", "title" => "Korea, Republic of", "iso_code" => "KR"],
            ["id" => "115", "title" => "Kuwait", "iso_code" => "KW"],
            ["id" => "116", "title" => "Kyrgyzstan", "iso_code" => "KG"],
            ["id" => "117", "title" => "Lao People's Democratic Republic", "iso_code" => "LA"],
            ["id" => "118", "title" => "Latvia", "iso_code" => "LV"],
            ["id" => "119", "title" => "Lebanon", "iso_code" => "LB"],
            ["id" => "120", "title" => "Lesotho", "iso_code" => "LS"],
            ["id" => "121", "title" => "Liberia", "iso_code" => "LR"],
            ["id" => "122", "title" => "Libyan Arab Jamahiriya", "iso_code" => "LY"],
            ["id" => "123", "title" => "Liechtenstein", "iso_code" => "LI"],
            ["id" => "124", "title" => "Lithuania", "iso_code" => "LT"],
            ["id" => "125", "title" => "Luxembourg", "iso_code" => "LU"],
            ["id" => "126", "title" => "Macau", "iso_code" => "MO"],
            ["id" => "127", "title" => "Macedonia", "iso_code" => "MK"],
            ["id" => "128", "title" => "Madagascar", "iso_code" => "MG"],
            ["id" => "129", "title" => "Malawi", "iso_code" => "MW"],
            ["id" => "130", "title" => "Malaysia", "iso_code" => "MY"],
            ["id" => "131", "title" => "Maldives", "iso_code" => "MV"],
            ["id" => "132", "title" => "Mali", "iso_code" => "ML"],
            ["id" => "133", "title" => "Malta", "iso_code" => "MT"],
            ["id" => "134", "title" => "Marshall Islands", "iso_code" => "MI"],
            ["id" => "135", "title" => "Martinique", "iso_code" => "MQ"],
            ["id" => "136", "title" => "Mauritania", "iso_code" => "MR"],
            ["id" => "137", "title" => "Mauritius", "iso_code" => "MU"],
            ["id" => "138", "title" => "Mexico", "iso_code" => "MX"],
            ["id" => "139", "title" => "Moldova, Republic of", "iso_code" => "MD"],
            ["id" => "140", "title" => "Monaco", "iso_code" => "MC"],
            ["id" => "141", "title" => "Mongolia", "iso_code" => "MN"],
            ["id" => "142", "title" => "Montserrat", "iso_code" => "MS"],
            ["id" => "143", "title" => "Morocco", "iso_code" => "MA"],
            ["id" => "144", "title" => "Mozambique", "iso_code" => "MZ"],
            ["id" => "145", "title" => "Myanmar", "iso_code" => "MM"],
            ["id" => "146", "title" => "Namibia", "iso_code" => "NA"],
            ["id" => "147", "title" => "Nauru", "iso_code" => "NR"],
            ["id" => "148", "title" => "Nepal", "iso_code" => "NP"],
            ["id" => "149", "title" => "Netherlands", "iso_code" => "NL"],
            ["id" => "150", "title" => "Netherlands Antilles", "iso_code" => "ANT"],
            ["id" => "151", "title" => "Neutral Zone (Saudi/Iraq)", "iso_code" => "NT"],
            ["id" => "152", "title" => "New Caledonia", "iso_code" => "NC"],
            ["id" => "153", "title" => "New Zealand", "iso_code" => "NZ"],
            ["id" => "154", "title" => "Nicaragua", "iso_code" => "NI"],
            ["id" => "155", "title" => "Niger", "iso_code" => "NE"],
            ["id" => "156", "title" => "Nigeria", "iso_code" => "NG"],
            ["id" => "157", "title" => "Niue", "iso_code" => "NU"],
            ["id" => "158", "title" => "Norfolk Island", "iso_code" => "NF"],
            ["id" => "159", "title" => "Northern Ireland", "iso_code" => "NIR"],
            ["id" => "160", "title" => "Northern Mariana Islands", "iso_code" => "NMI"],
            ["id" => "161", "title" => "Norway", "iso_code" => "NO"],
            ["id" => "162", "title" => "Oman", "iso_code" => "OM"],
            ["id" => "163", "title" => "Pakistan", "iso_code" => "PK"],
            ["id" => "164", "title" => "Palau", "iso_code" => "PAL"],
            ["id" => "165", "title" => "Palestinian Territory", "iso_code" => "PS"],
            ["id" => "166", "title" => "Panama", "iso_code" => "PA"],
            ["id" => "167", "title" => "Panama Canal Zone", "iso_code" => "PZ"],
            ["id" => "168", "title" => "Papua New Guinea", "iso_code" => "PG"],
            ["id" => "169", "title" => "Paraguay", "iso_code" => "PY"],
            ["id" => "170", "title" => "Peru", "iso_code" => "PE"],
            ["id" => "171", "title" => "Philippines", "iso_code" => "PH"],
            ["id" => "172", "title" => "Pitcairn Islands", "iso_code" => "PN"],
            ["id" => "173", "title" => "Poland", "iso_code" => "PL"],
            ["id" => "174", "title" => "Portugal", "iso_code" => "PT"],
            ["id" => "175", "title" => "Puerto Rico", "iso_code" => "PR"],
            ["id" => "176", "title" => "Qatar", "iso_code" => "QA"],
            ["id" => "177", "title" => "Reunion", "iso_code" => "RE"],
            ["id" => "178", "title" => "Romania", "iso_code" => "RO"],
            ["id" => "179", "title" => "Russian Federation", "iso_code" => "RU"],
            ["id" => "180", "title" => "Saint Kitts and Nevis", "iso_code" => "KN"],
            ["id" => "181", "title" => "Saint Lucia", "iso_code" => "LC"],
            ["id" => "182", "title" => "Samoa", "iso_code" => "WS"],
            ["id" => "183", "title" => "San Marino", "iso_code" => "SM"],
            ["id" => "184", "title" => "Sao Tome and Principe", "iso_code" => "ST"],
            ["id" => "185", "title" => "Saudi Arabia", "iso_code" => "SA"],
            ["id" => "186", "title" => "Scotland", "iso_code" => "SCT"],
            ["id" => "187", "title" => "Senegal", "iso_code" => "SN"],
            ["id" => "188", "title" => "Seychelles", "iso_code" => "SC"],
            ["id" => "189", "title" => "Sierra Leone", "iso_code" => "SL"],
            ["id" => "190", "title" => "Singapore", "iso_code" => "SG"],
            ["id" => "191", "title" => "Slovakia", "iso_code" => "SK"],
            ["id" => "192", "title" => "Slovenia", "iso_code" => "SI"],
            ["id" => "193", "title" => "Solomon Islands", "iso_code" => "SB"],
            ["id" => "194", "title" => "Somalia", "iso_code" => "SO"],
            ["id" => "195", "title" => "South Africa", "iso_code" => "ZA"],
            ["id" => "196", "title" => "Spain", "iso_code" => "ES"],
            ["id" => "197", "title" => "Sri Lanka", "iso_code" => "LK"],
            ["id" => "198", "title" => "Saint Helena", "iso_code" => "SH"],
            ["id" => "199", "title" => "Saint Pierre and Miquelon", "iso_code" => "PM"],
            ["id" => "200", "title" => "Saint Vincent and the Grenadines", "iso_code" => "VC"],
            ["id" => "201", "title" => "Sudan", "iso_code" => "SD"],
            ["id" => "202", "title" => "Suriname", "iso_code" => "SR"],
            ["id" => "203", "title" => "Svalbard and Jan Mayen", "iso_code" => "SJ"],
            ["id" => "204", "title" => "Swaziland", "iso_code" => "SZ"],
            ["id" => "205", "title" => "Sweden", "iso_code" => "SE"],
            ["id" => "206", "title" => "Switzerland", "iso_code" => "CH"],
            ["id" => "207", "title" => "Syrian Arab Republic", "iso_code" => "SY"],
            ["id" => "208", "title" => "Taiwan", "iso_code" => "TW"],
            ["id" => "209", "title" => "Tajikistan", "iso_code" => "TJ"],
            ["id" => "210", "title" => "Tanzania, United Republic of", "iso_code" => "TZ"],
            ["id" => "211", "title" => "Thailand", "iso_code" => "TH"],
            ["id" => "212", "title" => "Togo", "iso_code" => "TG"],
            ["id" => "213", "title" => "Tokelau", "iso_code" => "TK"],
            ["id" => "214", "title" => "Tonga", "iso_code" => "TO"],
            ["id" => "215", "title" => "Trinidad and Tobago", "iso_code" => "TT"],
            ["id" => "216", "title" => "Tunisia", "iso_code" => "TN"],
            ["id" => "217", "title" => "Turkey", "iso_code" => "TR"],
            ["id" => "218", "title" => "Turkmenistan", "iso_code" => "TM"],
            ["id" => "219", "title" => "Turks and Caicos Islands", "iso_code" => "TC"],
            ["id" => "220", "title" => "Tuvalu", "iso_code" => "TV"],
            ["id" => "221", "title" => "United States Minor Outlying Islands", "iso_code" => "UMI"],
            ["id" => "222", "title" => "Uganda", "iso_code" => "UG"],
            ["id" => "223", "title" => "Ukraine", "iso_code" => "UA"],
            ["id" => "224", "title" => "United Arab Emirates", "iso_code" => "AE"],
            ["id" => "225", "title" => "United Kingdom", "iso_code" => "GB"],
            ["id" => "226", "title" => "United States", "iso_code" => "US"],
            ["id" => "227", "title" => "Uruguay", "iso_code" => "UY"],
            ["id" => "228", "title" => "Uzbekistan", "iso_code" => "UZ"],
            ["id" => "229", "title" => "Vanuatu", "iso_code" => "VU"],
            ["id" => "230", "title" => "Holy See (Vatican City State)", "iso_code" => "VA"],
            ["id" => "231", "title" => "Venezuela", "iso_code" => "VE"],
            ["id" => "232", "title" => "Vietnam", "iso_code" => "VN"],
            ["id" => "233", "title" => "Virgin Islands, British", "iso_code" => "VG"],
            ["id" => "234", "title" => "Virgin Islands, U.S.", "iso_code" => "VUUSA"],
            ["id" => "235", "title" => "Wales", "iso_code" => "WLS"],
            ["id" => "236", "title" => "Wallis and Futuna", "iso_code" => "WF"],
            ["id" => "237", "title" => "Western Sahara", "iso_code" => "EH"],
            ["id" => "238", "title" => "Yemen", "iso_code" => "YE"],
            ["id" => "240", "title" => "Congo, Democratic Republic of the", "iso_code" => "CD"],
            ["id" => "241", "title" => "Zambia", "iso_code" => "ZM"],
            ["id" => "242", "title" => "Zimbabwe", "iso_code" => "ZW"],
            ["id" => "244", "title" => "Serbia", "iso_code" => "RS"],
            ["id" => "245", "title" => "Montenegro", "iso_code" => "ME"],
            ["id" => "246", "title" => "Kosovo", "iso_code" => "KSV"],
            ["id" => "243", "title" => "Worldwide", "iso_code" => "WW"],
        ];

        foreach ($data as $country) {
            Country::create($country);
        }
    }
}
